language: ocaml
sudo: required
os:
  - linux
env:
  - OCAML_VERSION=4.04
before_install:
  - scripts/travis-install_opam.sh
  - scripts/travis-install_python.sh
install:
  - eval `opam config env`
  - make setup
script:
  - make coverage
