name: Validate Pull Request
on: pull_request
jobs:
  execute-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          clean: false # Prevent removing files in 'path/to/base' folder.
      - name: Setup Ocaml
        uses: avsm/setup-ocaml@v1.1.10
        with:
          ocaml-version: 4.04.2
      - name: Setup Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'
      - run: pip install virtualenv
      - run: make setup
          env:
            OPAMSOLVERTIMEOUT: 300
      - run: make coverage
