name: Validate Pull Request
on: pull_request
jobs:
  execute-tests:
    runs-on: macos-latest
    steps:
      - uses: tapthaker/actions-ocaml@0.1
        with:
          ocaml_version: 4.04.2
      - run: eval `opam config env`
      - run: make setup
      - run: make coverage
